services:
  - type: web
    name: zooyorktimes-scraper
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: MONGODB_URI
        sync: false
      - key: REACT_APP_NYT_API_KEY
        sync: false
